### PR TITLE
Add Buffer (BUFS) token

### PR DESCRIPTION
**Pull request by BierblikRick**
This pull request adds the Buffer (BUFS) token

### CODE REVIEW

**Comment by nmelentjevs** [comment]
missing tx hash and image

**Comment by ben221199** [comment]
Image:
bufferbufs

**Comment by ben221199** [comment]
TX Hash: `c90bb0a936acdcac485176ce63b20069cef3349faf34d7ca48f077cd0a2f0741`

**Comment by ben221199** [comment]
@nmelentjevs Do you have enough information?

**Comment by ben221199** [comment]
@nmelentjevs Bump.

**Comment by nmelentjevs** [comment]
Verified

**Comment by nmelentjevs** [comment]
Verified, closing due to rebase

**Pull request closed without merging**
