### PR TITLE
Adds $BAG token

### PR DESCRIPTION
**Pull request by dontfumblethebag**

### CODE REVIEW

**Comment by nmelentjevs** [comment]
missing image, missing payment tx hash

**Comment by dontfumblethebag** [comment]
Here's the logo. We will follow up in a bit with the payment tx
cOUd_SBh_400x400

**Comment by dontfumblethebag** [comment]
TX Of payment:
https://cardanoscan.io/transaction/5f3ccdb7663c433168139cdc083443e5946e5dd0e8574d6321e6d1dee332a7a2

**Comment by dontfumblethebag** [comment]
Thanks!

**Pull request merged**
